### ISSUE TITLE
Does not run

### ISSUE THREAD

**Issue by probonopd** [pipam/pipam#2]
Unfortunately I get an error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'then-utils'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/tmp/.mount_qGLEaY/usr/bin/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/.mount_qGLEaY/usr/bin/resources/app.asar/index.js:8:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```
This is when using the 1.0.1 AppImage on Ubuntu 16.04.

**Comment by facekapow** [comment]
Interesting... this seems to hint that the `node_modules` folder isn't being included in the AppImage. I can't test out myself right now (performing a release upgrade on my Ubuntu machine) but as soon as I can I'll try to debug this and see what's going on.

**Comment by facekapow** [comment]
Should be fixed in the latest build, can you verify it launches?

**Comment by probonopd** [comment]
I can verify that the application launches now.
